# Generated by Django 4.2.10 on 2025-11-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("FRUITS", "Fruits"),
                    ("VEGETABLES", "Vegetables"),
                    ("GRAINS", "Grains & Cereals"),
                    ("TUBERS", "Root Crops & Tubers"),
                    ("HERBS", "Herbs & Spices"),
                    ("DAIRY", "Dairy & Eggs"),
                    ("MEAT", "Meat & Poultry"),
                    ("SEAFOOD", "Seafood"),
                    ("PROCESSED", "Processed Foods"),
                    ("BEVERAGES", "Beverages"),
                    ("ORGANIC", "Organic Products"),
                    ("OTHERS", "Other Agricultural Products"),
                ],
                default="FRUITS",
                help_text="Select the most appropriate category for your product",
                max_length=50,
            ),
        ),
    ]
