# Generated by Django 4.2.10 on 2025-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KG", "per kilogram (kg)"),
                    ("G", "per gram (g)"),
                    ("PC", "per piece"),
                    ("SACK", "per sack"),
                    ("BUNCH", "per bunch"),
                    ("LITRE", "per litre (L)"),
                    ("ML", "per millilitre (ml)"),
                    ("DOZEN", "per dozen"),
                    ("PACK", "per pack"),
                    ("BOX", "per box"),
                ],
                default="KG",
                help_text="Select the unit of measurement for pricing",
                max_length=10,
            ),
        ),
    ]
