# Generated by Django 4.2.10 on 2025-11-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="shipping_address",
            field=models.TextField(
                blank=True, help_text="Default shipping address for orders", null=True
            ),
        ),
    ]
